
import { ContentItem, Fields } from 'kentico-cloud-delivery';

/**
* This class was generated by 'kentico-cloud-model-generator-utility' at Wed Apr 24 2019 12:52:58 GMT-0400 (Eastern Daylight Time).
*/
export class Cereal extends ContentItem {
        constructor() {
        super({
            propertyResolver: ((fieldName) => {
                if (fieldName === 'name_of_cereal') {
                    return 'nameOfCereal';
                }
                if (fieldName === 'rich_color_picker') {
                    return 'richColorPicker';
                }
                if (fieldName === 'cereal_pic') {
                    return 'cerealPic';
                }
                if (fieldName === 'yuriy_s_custom_element') {
                    return 'yuriySCustomElement';
                }
                return fieldName;
            })
        });
    }
}
