
import { ContentItem, Fields } from 'kentico-cloud-delivery';

/**
* This class was generated by 'kentico-cloud-model-generator-utility' at Wed Apr 24 2019 12:52:58 GMT-0400 (Eastern Daylight Time).
*/
export class Testimage extends ContentItem {
        constructor() {
        super({
            propertyResolver: ((fieldName) => {
                if (fieldName === 'example_688c282__meta_keywords') {
                    return 'example688c282MetaKeywords';
                }
                if (fieldName === 'example_688c282__meta_description') {
                    return 'example688c282MetaDescription';
                }
                if (fieldName === 'test_image') {
                    return 'testImage';
                }
                return fieldName;
            })
        });
    }
}
