
import { ContentItem, Fields } from 'kentico-cloud-delivery';

/**
* This class was generated by 'kentico-cloud-model-generator-utility' at Wed Apr 24 2019 12:52:58 GMT-0400 (Eastern Daylight Time).
*/
export class Tweet extends ContentItem {
        constructor() {
        super({
            propertyResolver: ((fieldName) => {
                if (fieldName === 'tweet_link') {
                    return 'tweetLink';
                }
                if (fieldName === 'display_options') {
                    return 'displayOptions';
                }
                return fieldName;
            })
        });
    }
}
